// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dpt.proto

package dpt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Size struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf931162ea2364d8, []int{0}
}

func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (m *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(m, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

func (m *Size) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Dpt struct {
	Trid                 int32         `protobuf:"varint,1,opt,name=trid,proto3" json:"trid,omitempty"`
	Eventime             int64         `protobuf:"varint,2,opt,name=eventime,proto3" json:"eventime,omitempty"`
	Askbook              []*Dpt_DptBar `protobuf:"bytes,3,rep,name=askbook,proto3" json:"askbook,omitempty"`
	Bidbook              []*Dpt_DptBar `protobuf:"bytes,4,rep,name=bidbook,proto3" json:"bidbook,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Dpt) Reset()         { *m = Dpt{} }
func (m *Dpt) String() string { return proto.CompactTextString(m) }
func (*Dpt) ProtoMessage()    {}
func (*Dpt) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf931162ea2364d8, []int{1}
}

func (m *Dpt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dpt.Unmarshal(m, b)
}
func (m *Dpt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dpt.Marshal(b, m, deterministic)
}
func (m *Dpt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dpt.Merge(m, src)
}
func (m *Dpt) XXX_Size() int {
	return xxx_messageInfo_Dpt.Size(m)
}
func (m *Dpt) XXX_DiscardUnknown() {
	xxx_messageInfo_Dpt.DiscardUnknown(m)
}

var xxx_messageInfo_Dpt proto.InternalMessageInfo

func (m *Dpt) GetTrid() int32 {
	if m != nil {
		return m.Trid
	}
	return 0
}

func (m *Dpt) GetEventime() int64 {
	if m != nil {
		return m.Eventime
	}
	return 0
}

func (m *Dpt) GetAskbook() []*Dpt_DptBar {
	if m != nil {
		return m.Askbook
	}
	return nil
}

func (m *Dpt) GetBidbook() []*Dpt_DptBar {
	if m != nil {
		return m.Bidbook
	}
	return nil
}

type Dpt_DptBar struct {
	Price                float32  `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
	Qty                  float32  `protobuf:"fixed32,2,opt,name=qty,proto3" json:"qty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dpt_DptBar) Reset()         { *m = Dpt_DptBar{} }
func (m *Dpt_DptBar) String() string { return proto.CompactTextString(m) }
func (*Dpt_DptBar) ProtoMessage()    {}
func (*Dpt_DptBar) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf931162ea2364d8, []int{1, 0}
}

func (m *Dpt_DptBar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dpt_DptBar.Unmarshal(m, b)
}
func (m *Dpt_DptBar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dpt_DptBar.Marshal(b, m, deterministic)
}
func (m *Dpt_DptBar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dpt_DptBar.Merge(m, src)
}
func (m *Dpt_DptBar) XXX_Size() int {
	return xxx_messageInfo_Dpt_DptBar.Size(m)
}
func (m *Dpt_DptBar) XXX_DiscardUnknown() {
	xxx_messageInfo_Dpt_DptBar.DiscardUnknown(m)
}

var xxx_messageInfo_Dpt_DptBar proto.InternalMessageInfo

func (m *Dpt_DptBar) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Dpt_DptBar) GetQty() float32 {
	if m != nil {
		return m.Qty
	}
	return 0
}

func init() {
	proto.RegisterType((*Size)(nil), "dpt.Size")
	proto.RegisterType((*Dpt)(nil), "dpt.Dpt")
	proto.RegisterType((*Dpt_DptBar)(nil), "dpt.Dpt.DptBar")
}

func init() { proto.RegisterFile("dpt.proto", fileDescriptor_bf931162ea2364d8) }

var fileDescriptor_bf931162ea2364d8 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x29, 0x28, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x29, 0x28, 0x51, 0x92, 0xe2, 0x62, 0x09, 0xce,
	0xac, 0x4a, 0x15, 0x12, 0xe2, 0x62, 0x29, 0xce, 0xac, 0x4a, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60,
	0x0d, 0x02, 0xb3, 0x95, 0xf6, 0x32, 0x72, 0x31, 0xbb, 0x14, 0x94, 0x80, 0xe4, 0x4a, 0x8a, 0x32,
	0x53, 0x60, 0x72, 0x20, 0xb6, 0x90, 0x14, 0x17, 0x47, 0x6a, 0x59, 0x6a, 0x5e, 0x49, 0x66, 0x6e,
	0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x9c, 0x2f, 0xa4, 0xc9, 0xc5, 0x9e, 0x58, 0x9c,
	0x9d, 0x94, 0x9f, 0x9f, 0x2d, 0xc1, 0xac, 0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0xaf, 0x07, 0xb2, 0xd5,
	0x05, 0x82, 0x9d, 0x12, 0x8b, 0x82, 0x60, 0xf2, 0x20, 0xa5, 0x49, 0x99, 0x29, 0x60, 0xa5, 0x2c,
	0x38, 0x94, 0x42, 0xe5, 0xa5, 0x0c, 0xb8, 0xd8, 0x20, 0x42, 0x42, 0x22, 0x5c, 0xac, 0x05, 0x45,
	0x99, 0xc9, 0x10, 0xc7, 0x32, 0x05, 0x41, 0x38, 0x42, 0x02, 0x5c, 0xcc, 0x85, 0x25, 0x95, 0x60,
	0xc7, 0x30, 0x05, 0x81, 0x98, 0x49, 0x6c, 0x60, 0x7f, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x94, 0x93, 0x18, 0x2a, 0xf4, 0x00, 0x00, 0x00,
}
